<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Embedding PHP in HTML</title>
</head>
<body>

<h1>This is plan HTML</h1>
<p>So is this</p>

<p>This is HTML, but the date is generated by PHP: <?php echo date('l'); ?></p>

</body>
</html>